#!/bin/bash

echo "All variables passesd to the script: $@"
echo "Number of variables: $#"
echo "Script name: $0"
echo "current Directory: $PWD"
echo  "User running this script: $USER"
echo "Home directorry of user: $HOME"
echo "PID of the script: $$"
sleep 10 &
echo "PID of last command in background: $!"

